name: Deploy to Railway

on:
  push:
    branches: [main]  # Runs the workflow on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest  # Uses the Railway CLI container

    env:
      SVC_ID: python-finalproj  # Replace with your actual Railway Service ID
      RAILWAY_TOKEN: ${{ secrets.PYTHON_API_RAILWAY_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Clones the repo into the GitHub runner

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"  # Ensure it matches your Flask app's Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

    
      - name: Deploy to Railway
        run: railway up --service=${{ env.PYTHON_API_RAILWAY_TOKEN }}  # Deploys to Railway

        # PYTHON_API_RAILWAY_TOKEN=b6b7c357-232d-47cb-b48b-d17dc1c0e707 railway up
